### ISSUE TITLE
NuxtLink in naive ui's menu

### ISSUE THREAD

**Issue by orenmizr** [becem-gharbi/nuxt-naiveui#11]
i can't seem to use nuxtlink inside the naive ui menu's menuOptions. do you have a workaround for this ? @becem-gharbi 

edit: i managed to wrap nuxt link in a new component NLink and use it inside menuOptions

```
export default defineNuxtLink({
  componentName: 'NLink'
})
```

would love to remove this workaround.

**Comment by becem-gharbi** [comment]
You can have a look at `NaiveNavbar` custom component which uses `NMenu` for navigation. [link](https://github.com/becem-gharbi/nuxt-naiveui/blob/dea92b9920a6aead27dab416d6aa3a10c0e8f967/src/runtime/components/NaiveNavbar.vue#L117)

**Comment by orenmizr** [comment]
thanks, it worked. is the # sign an alias for nuxt inner components ? cause it is not the component folder in that example.

**Comment by becem-gharbi** [comment]
What # sign?

**Comment by orenmizr** [comment]
import { NuxtLink } from "#components"   <-- - this one

this is an explicit import. i guess bypassing the auto import solved it since the component is used not in the template (pug) but inside the script tag which did not know how to auto import

**Comment by becem-gharbi** [comment]
It's a nuxt virtual file system that exports all components for auto-import.

**Comment by orenmizr** [comment]
appreciate the answer. because it is nuxt's element - i thought it would put it in the autimports.  i am exploring nuxt3 with pug as a template. it seem that i have to explicitly import something that is not in the template scope.

**Comment by becem-gharbi** [comment]
As far as I know, there is a nuxt module [@nuxt/components](https://github.com/nuxt/components) at least for Nuxt 2 that handles the auto imports of components. The components are parsed [here](https://github.com/nuxt/components/blob/86ab5e0b508186f647c3d79ac4a4cc67cae11f19/src/tagExtractor.ts#L12) with `vue-template-compiler`.

**Comment by becem-gharbi** [comment]
If you are using Vscode you just need [Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar) extension.

**Comment by orenmizr** [comment]
i do use vscode. plus volar. plus @volar/vue-language-plugin-pug :) i think the framework has to submit a typescript components list to vue + bundler. nevermind, this setup is good enough.
