### ISSUE TITLE
nuxt 3.7 defineNuxtModule hooks prepare:types

### ISSUE THREAD

**Issue by yapengsoft** [becem-gharbi/nuxt-naiveui#14]
![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/75244754/927cb16a-d931-4e4e-bf0e-19f3defe682e)
I upgraded nuxt to 3.7 and unfortunately there is a problem

tsConfig.compilerOptions no longer provides a “types” attribute

**Comment by becem-gharbi** [comment]
Yes, you can downgrade to 3.6 for now, I will fix this later.

**Comment by yapengsoft** [comment]
Okay, Thanks for your work

**Comment by becem-gharbi** [comment]
This issue is fixed on [v1.2.7](https://github.com/becem-gharbi/nuxt-naiveui/releases/tag/v1.2.7).
