### ISSUE TITLE
ERROR  Cannot read properties of undefined (reading 'push') 

### ISSUE THREAD

**Issue by orenmizr** [becem-gharbi/nuxt-naiveui#15]
when running pnpm + this 1.2.6. i updated packages and fell into it :/

fails on this block. any idea of what to check ?  

/ Add types for volar
  hooks: {
    "prepare:types": ({ tsConfig, references }) => {
      tsConfig.compilerOptions.types.push("naive-ui/volar");
      **references**.push({
        types: "naive-ui/volar"
      });
    }
  },

**Comment by megasanjay** [comment]
This seems to be an issue with Nuxt 3.7

Temporary fix until the library is updated - https://github.com/nuxt/nuxt/discussions/22823#discussioncomment-6829223

For @becem-gharbi: It seems to be a simple fix. Nuxt Swiper has updated its library for the same issue - https://github.com/cpreston321/nuxt-swiper/pull/85

**Comment by orenmizr** [comment]
thanks for the quick response. doesn't nullify the default behaviour by giving it a [] override ?

**Comment by megasanjay** [comment]
I believe it is only supposed to extend, not overwrite: [nuxt-config#tsconfig](https://nuxt.com/docs/api/configuration/nuxt-config#tsconfig)

**Comment by orenmizr** [comment]
alright. 10x. it did remove the error : )

**Comment by becem-gharbi** [comment]
This issue is fixed on [v1.2.7](https://github.com/becem-gharbi/nuxt-naiveui/releases/tag/v1.2.7).

**Comment by orenmizr** [comment]
upgraded to the latest version. also solved my  flash of unstyled content. great  : )
