### ISSUE TITLE
Can you remove unplugin

### ISSUE THREAD

**Issue by kuizuo** [becem-gharbi/nuxt-naiveui#2]
we can use  `addComponent` of `@nuxt/kit` to replace `unplugin-vue-components` and `addImports` to replace `unplugin-auto-import`. such as:

```typescript
import naive from 'naive-ui'
const naiveComponents = Object.keys(naive).filter((name) =>
  /^N[A-Z]*/.test(name)
)

const naiveComposables = [
  'useDialog',
  'useDialogReactiveList',
  'useLoadingBar',
  'useMessage',
  'useNotification',
  'useThemeVars'
]

// add imports for naive-ui components
naiveComponents.forEach((name) => {
  addComponent({
    export: name,
    name: name,
    filePath: "naive-ui",
  })
})

// add imports for naive-ui composables
naiveComposables.forEach((name) => {
  addImports({
    name: name,
    as: name,
    from: 'naive-ui'
  })
})
```

Because `naive-ui` components and composables are placed under src folder. So I can only use the following code to get all the components.

```
const naiveComponents = Object.keys(naive).filter((name) =>
  /^N[A-Z]*/.test(name)
)
```
other than

```
import { components as naiveComponents } from 'naive'
```

I don't know if I'm going to lose any components or composables by doing this.

**Comment by becem-gharbi** [comment]
Thanks @kuizuo for noticing that.

Indeed, Uplugin is not needed as the auto import is already built into Nuxt. As for components and composables, they are exported at the src level. So clearly there is no lose.

You can look for the [component resolver](https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/naive-ui.ts)  at unplugin-vue-component for reference.
