### ISSUE TITLE
After generate, the index.html has a lot of styles !

### ISSUE THREAD

**Issue by Eacolt** [becem-gharbi/nuxt-naiveui#20]
Hello, I really need you help!

 When I use `npm run generate` , to build my SSG project,  I found the public index.html, its has a lot of style tags looks like:
`<style cssr-id="n-button">.n-button ...`

how to hidden this tags ?    how to put them in link, just a .css file? 

<img width="796" alt="image" src="https://github.com/becem-gharbi/nuxt-naiveui/assets/15901920/2d917b35-81a8-431c-81fd-59030a1ccc11">

<img width="700" alt="image" src="https://github.com/becem-gharbi/nuxt-naiveui/assets/15901920/71b3ab7b-ba0d-4dcd-83ef-bd26ee3aeae3">

**Comment by becem-gharbi** [comment]
Hi, this is how naive-ui works, no static css, styles are compiled with js at runtime and returned on the `head` tag. You can check the [plugin](https://github.com/becem-gharbi/nuxt-naiveui/blob/main/src/runtime/plugins/naive.server.ts) behind this. 
I believe that this implementation is much more performant than serving a large stylesheet with unused and duplicated styles.
