### ISSUE TITLE
Mobile "theme" causes layout shifts

### ISSUE THREAD

**Issue by T0TProduction** [becem-gharbi/nuxt-naiveui#21]
Hi there!

First of all, thanks for the great work and making it super easy to use naive-ui with nuxt! I used to use it "manually", but now am starting to switch to this library. During this I found one issue I can't seem to be able to get rid of:
Due to how theming is handled here, we don't only have light and dark themes, but also a mobile theme.

This theme in particular is something that will always cause layout shifts for me due to the fact that my completely SSR rendered, statically deployed page will not know if the device is a mobile device or not, and then change sizes of various things once it's loaded on the client and detects mobile/tablet. For me personally, disabling/getting rid of the mobile theme entirely would be the best solution.

It's nice how we can control the color themes with the composable, e.g. by forcing a specific one, or setting a default/preferred one.
I was hoping to find a similar utility to force/disable the mobile theme, but can't seem to find any solution.
Another option I thought of but didnt get working is somehow setting the ThemeConfig.mobile to an empty object or false. Obviously this didn't work since the themes are being merged, thus essentially falling back to the default mobile theme.

I would love to see any of the above mentioned, or another alternative solution to this, being included in a future version, and would also be open to working on it in a PR myself.

I primarily wanted to double check that this is currently indeed not possible, and if you are open to adding such an option.

For me personally, I think something close to the option of setting 
```
{
...
mobile: false,
...
}
```
in the `ThemeConfig` , and this, instead of merging, disabling mobile theme (or setting it to empty) entirely seems the best and also easiest in terms of being both easy to understand as well as not being breaking.

Please let me know what you think and how we could continue on this!

---
For reference, this is the PR where I'm migrating to use this library https://github.com/T0TProduction/diluz.io/pull/202 as well as a preview deployment of it to show the layout shift: https://deploy-preview-202--diluzio.netlify.app/sebastian

**Comment by becem-gharbi** [comment]
Hi, thanks for the feedback,

Indeed with pre-rendering such issues may show up on hydration. To be honest I believe that if dynamic theming is needed, pre-rendering should be prevented. In your case, on `NaiveConfig` , You can override the `mobile` and `mobileOrTablet` properties against the defaults. I agree that there should be a better solution to this like optional defaults. Feel free to open a PR if you have an idea in mind :)

```ts
export default {
  common: {
    fontSize: "14px",
    heightMedium: "34px",
    fontSizeMedium: "14px",
  },
  Form: {
    labelFontSizeTopMedium: "14px",
  },
  Input: {
    heightMedium: "34px",
    fontSizeMedium: "14px",
  },
  Button: {
    heightMedium: "34px",
    fontSizeMedium: "14px",
  },
  Card: {
    fontSizeMedium: "14px",
  },
  Avatar: {
    heightMedium: "34px",
    fontSize: "14px",
  },
  ColorPicker: {
    heightMedium: "34px",
    fontSizeMedium: "14px",
  },
  Dropdown: {
    optionHeightMedium: "34px",
    fontSizeMedium: "14px",
  },
  Radio: {
    buttonHeightMedium: "34px",
    fontSizeMedium: "14px",
  },
  Skeleton: {
    heightMedium: "34px",
  },
  Tag: {
    heightMedium: "34px",
    fontSizeMedium: "14px",
  },
  Result: {
    fontSizeMedium: "14px",
  },
  Tabs: {
    tabFontSizeMedium: "14px",
  },
};

```

**Comment by T0TProduction** [comment]
Thanks for the quick response!

I'll try out the snippet you shared.

Regardless of the outcome, I might create a small PR to make the theme defaults optional, I think that sounds doable and also potentially useful to others.

**Comment by becem-gharbi** [comment]
As I have a planned release v1.4.4, I just included a fix to this issue. You can check https://nuxt-naiveui.bg.tn/components/naive-config

**Comment by T0TProduction** [comment]
Thanks for adding that so quickly! I tried it out and it works perfectly
