### ISSUE TITLE
How to disable initialize cookie `naive_color_mode_preference`

### ISSUE THREAD

**Issue by shiny** [becem-gharbi/nuxt-naiveui#22]
When start a new page, nuxt-naiveui will automatically set `naive_color_mode_preference` 
But GDPR policy requires no cookie if user is not accepted.

How to control it in the first time which user haven't click the `ACCEPT ALL` button?

**Comment by becem-gharbi** [comment]
As far as I know, if a cookie is essential for the website to function then it's exempted from this policy.
