### ISSUE TITLE
typeerror in NaiveNavbar.vue

### ISSUE THREAD

**Issue by kryopix** [becem-gharbi/nuxt-naiveui#23]
Hello,

Firstly, I want to express my gratitude for this outstanding module.

I have identified a TypeScript error that can be easily resolved. However, when the TypeScript check is enabled in Nuxt, it becomes quite troublesome due to the numerous error messages generated during the build process, stemming from the interaction with the props.

The type error is located within the NaiveNavbar.vue file, specifically related to the 'sticky' property.

When this property shares the same key as the constant 'sticky,' it results in multiple TypeScript errors like the following:
```
ERROR(vue-tsc)  Property 'backIcon' does not exist on type 'never'.
  The intersection '{ $: ComponentInternalInstance; $data: {}; $props: { routes?: NavbarRoute[] | undefined; drawerRoutes?: NavbarRoute[] | undefined; ... 21 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R) => an...' was reduced to 'never' because property 'sticky' has conflicting types in some constituents.
```

To resolve this issue, you can follow one of these working solutions:
- Rename the prop 'sticky' to 'stick.'
- Rename the constant 'sticky' to 'stick.'

Here is the relevant code snippet:
```js
const props = withDefaults(
  defineProps<{
    routes?: NavbarRoute[]
    drawerRoutes?: NavbarRoute[]
    menuToggleIcon?: string
    menuToggleIconSize?: number
    backIcon?: boolean
    backIconSize?: number
    menuInverted?: boolean
    menuPlacement?: 'right' | 'left' | 'center'
    drawerPlacement?: 'top' | 'right' | 'bottom' | 'left'
    stick?: boolean
    drawerClosable?: boolean
    drawerWidth?: string | number
  }>(),
  {
    routes: () => [],
    drawerRoutes: () => [],
    menuToggleIcon: 'ph:equals',
    menuPlacement: 'left',
    drawerPlacement: 'left',
    menuInverted: false,
    stick: true,
    menuToggleIconSize: 26,
    backIcon: false,
    backIconSize: 26,
    drawerWidth: '100%',
    drawerClosable: true
  }
)

const sticky = computed(() => (props.stick ? 'sticky' : 'static'))
```
I hope this helps resolve the issue. Thank you for your great work on this module!

Best regards,

**Comment by becem-gharbi** [comment]
Thanks, appreciate the advice. From now on I will make sure to run typecheck on release workflow to solve this kind of issues.
