### ISSUE TITLE
iconSize support string

### ISSUE THREAD

**Issue by lulucas** [becem-gharbi/nuxt-naiveui#25]
```
 <n-icon size="40">
    <naive-icon name="xxx" />
  </n-icon>
```
For better compatibility with Naive Icon component size props.

  naiveui: {
    iconSize: "1em",
  }

Maybe

type Unit = 'px' | 'rem' | 'em' | '%';

```
interface PublicConfig {
    themeConfig?: ThemeConfig;
    colorModePreference: ColorModePreference;
    iconSize: number | `${number}${Unit}`;
}
```

**Comment by becem-gharbi** [comment]
The `NaiveIcon` component is composed of Iconify icon wrapped with `NIconWrapper` naive-ui component. The latter only accepts numbers for sizing. Thus the `size` prop can only be a number.
