### ISSUE TITLE
colorModePreference not work on mobile device and Safari.

### ISSUE THREAD

**Issue by teknotut** [becem-gharbi/nuxt-naiveui#27]
Hi,

Thanks for fix [26](https://github.com/becem-gharbi/nuxt-naiveui/issues/26), its work without error now.

I tried using colorModePreference to switch between dark and light modes, and it worked when using Chrome or Firefox browsers on a PC. However, it didn't work when tested on a mobile device or Safari. I could switch modes on one page, but when navigating to another page, the color mode reverted back to light.

Here my script for switch dark/light.
```
<script setup>
import { ref } from 'vue'
const { colorModePreference } = useNaiveColorMode();

var theme = useCookie('naive_color_mode_preference')

const toggleDark = (t) => colorModePreference.set(t === 'light' ? 'dark' : 'light');
</script>
```

It seems that this issue might be related to the use of cookies, which may not work as expected in browsers with stricter privacy settings.

I try to use localstorage like this:
```
import { ref, onMounted } from 'vue'
const { colorModePreference } = useNaiveColorMode();

var theme = ref('light')

const toggleDark = (t) => {
    const newTheme = t === 'light' ? 'dark' : 'light'
    colorModePreference.set(newTheme)
    theme.value = newTheme
    localStorage.setItem('theme', newTheme)
}

onMounted(() => {
    if (localStorage.getItem('theme') === 'dark') {
        theme.value = 'dark'
    }
})
```

But still not work in Safari or Mobile device, maybe because colorModePreference try to get from cookie value.

My suggestion is that it might be better to store the state in localStorage rather than using cookies.

**Comment by becem-gharbi** [comment]
Have you tried with `NaiveColorModeSwitch` ? also make sure that colorMode is not forced. The cookie storage is needed for SSR.

**Comment by becem-gharbi** [comment]
Have you tried with `NaiveColorModeSwitch` ? also make sure that colorMode is not forced. The cookie storage is needed for SSR.

**Comment by teknotut** [comment]
Use NaiveColorModeSwitch still not work in safari and mobile device, but I think if published in valid domain (not localhost) can work, I try latter for that.
Thanks you :)

**Comment by teknotut** [comment]
Hi, its work when I using domain both colorModePreference and NaiveColorModeSwitch all work. So problem maybe because safari and mobile cannot accept cookie with localhost.

Thanks you :)

**Comment by teknotut** [comment]
Hi, its work when I using domain both colorModePreference and NaiveColorModeSwitch all work. So problem maybe because safari and mobile cannot accept cookie with localhost.

Thanks you :)
