### ISSUE TITLE
TypeError: Cannot set properties of null (setting 'nodeValue')

### ISSUE THREAD

**Issue by mjsy** [becem-gharbi/nuxt-naiveui#28]
Hi,

This error seems to be thrown when trying to update a ref that was first undefined (or null / empty string) and used as the only value of some components (I tried the typography ones):

![screenshot](https://github.com/becem-gharbi/nuxt-naiveui/assets/7572669/5813f53a-6935-4f41-ba6b-e0ca02e70a54)

Here is an example of code leading to this error :

```
<template>
  <div>
    <n-text>{{ test }}</n-text>
  </div>
</template>

<script lang="ts" setup>
const test = ref<string>() // ref<string>('') will give the same error

onMounted(() => {
  setTimeout(() => test.value = 'test', 1000)
})
</script>
```

It happens only in SRR mode and only when the value is directly used as the component scope, so doing this would avoid the bug:

```
<n-text><span>{{ test }}</span></n-text>
````

The same test without a naive-ui component or without SSR works just fine.

Maybe it's a bug with naive-ui and not just this plugin?

**Comment by becem-gharbi** [comment]
This looks to be related to `naive-ui`. Any case, you can try wrapping the component with `ClientOnly`.
