### ISSUE TITLE
cooperation

### ISSUE THREAD

**Issue by productdevbook** [becem-gharbi/nuxt-naiveui#29]
Here was the library where I started more than a year ago. But I realized today that it creates the same thing and has progressed a lot.

https://github.com/huntersofbook/naive-ui-nuxt

If you want to cooperate, I can deactivate my library or you can move to our side.

It's up to you. Having 2 identical libraries is not a good thing.

**Comment by becem-gharbi** [comment]
Thanks for this proposition. 

The SSR support is already provided by `naive-ui` as explained in [docs](https://www.naiveui.com/en-US/os-theme/docs/ssr). This module provides extra features, you can check this issue (#9). 

Thanks for your understanding.

**Comment by productdevbook** [comment]
I think you don't understand that there are 2 npm packages for the same topic. If you make a decision on what I wrote above, let's proceed accordingly.

**Comment by becem-gharbi** [comment]
These are 2 npm packages for this same topic with different goals and features. That's a good thing! 
If you have ideas in mind to move this work forward, your contributions would be very appreciated!

**Comment by productdevbook** [comment]
No, it's not a good thing, people need to focus on one place.

I'm closing my project. I'll forward it to you.

**Comment by productdevbook** [comment]
![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/38668796/7b5355ac-8bb3-45a0-ac51-72ee4b88c199)


I referred him to you.

**Comment by becem-gharbi** [comment]
> people need to focus on one place

People choose the best for them, It's not up to us to decide. And please refer to this issue as well.
