### ISSUE TITLE
 Is it possible to use phosphor icons on a <n-dropdown>?

### ISSUE THREAD

**Issue by phinolex** [becem-gharbi/nuxt-naiveui#31]
Hello,

First of all, I wanted to thank you immensely for creating this GitHub repository! It is truly very useful to me!

I must now bring up a challenge I am facing: I'm desperately trying to integrate icons from phosphoricons.com (present in your nuxt-naiveui repo) into my <n-dropdown>, to no avail.

When I place  `<naive-icon name="ph-globe"></naive-icon>` in my template , the icon works perfectly.

But as soon as I try to render in the n-dropdown with phosphoricons, it seems like the `<naive-icon>` component is not being read.

When I inspect the DOM html element, `<naive-icon name=""></naive-icon>`  does indeed appear in the dropdown, but the component seems to not be read.

I suspect I might have made an error somewhere, but it's not at all clear to me. Is it possible to add phosphor icons from the naive-icon component to a <n-dropdown>? 

Here is my complete code: 
```
<template> 
  <!-- This icon work -->    
  <naive-icon name="ph-user"></naive-icon>
  
  <n-dropdown :options="options">
              <n-button>
                       my button
              </n-button>
      </n-dropdown>
</template>

<script>
/* Icons don't work */
const renderIcon = (iconClass) => {
  return () => h("naive-icon", { name: iconClass });
};

const options = [
  {
    label: "My Profil",
    icon: renderIcon('ph-user'),
    key: "Profil",
  },
  {
    label: "Setting",
    icon: renderIcon('ph-gear-six'),
    key: "Setting",
  },
  {
    label: "Disconnected",
    icon: renderIcon('ph-sign-out'),
    key: "Disconnected",
  }
];


export default {
  setup() {
    return {
      options,
    };
  },
}
</script> 
```

**Comment by becem-gharbi** [comment]
Hi, thanks for the feedback

The render function `h` in this case should accept the component itself and not just its name. 

Can you try the following,

```js
#import { NaiveIcon } from "#components" // Needs to be manually imported

//
h(NaiveIcon, { name: iconClass });
//
```

**Comment by phinolex** [comment]
Thank you for your prompt response @becem-gharbi!

The solution `import { NaiveIcon } from "#components"` works now ! 
Thank you so much!
