### ISSUE TITLE
[vue warn] onScopeDispose for useNaiveColorMode

### ISSUE THREAD

**Issue by lulucas** [becem-gharbi/nuxt-naiveui#34]
```
[Vue warn] onScopeDispose() is called when there is no active effect scope to be associated 	cookieRef	@	cookie.js:111
useCookie	@	cookie.js:25
set	@	useNaiveColorMode.mjs:29
(anonymous)	@	colorMode.mjs:15
```
And I don't need to dynamically configure the color mode. Is there any way to avoid generating the cookie naive_color_mode_preference?

**Comment by becem-gharbi** [comment]
Thanks for reporting this warning. To make sure I understand well, Do you need to remove the vue warning or to optionally disable colorMode feature?

**Comment by lulucas** [comment]
> Thanks for reporting this warning. To make sure I understand well, Do you need to remove the vue warning or to optionally disable colorMode feature?

This is two issues. This issue should resolve the vue warn problem. The other issue is the suggestion that when colorMode is not explicitly specified, it should only use the default value 'light' in memory, without generating extra cookies.

**Comment by becem-gharbi** [comment]
Can you create a new issue for the proposition and describe the expected behaviour?

**Comment by lulucas** [comment]
Thanks for your job.
