### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')

### ISSUE THREAD

**Issue by Lgowen** [becem-gharbi/nuxt-naiveui#35]
when i use this component
<n-select v-model:value="model.scene" placeholder="xxxx" :options="options" />
const model = ref({
  page: '/page/index/index',
  pageQuery: '',
  scene: ''
})

const options = [
  {
    label: 'ch_appcenter',
    value: 'ch_appcenter'
  },
]

</script>

it will show me bug for 
<img width="1297" alt="image" src="https://github.com/becem-gharbi/nuxt-naiveui/assets/62790161/0c5e23ae-1888-4953-9313-a267f59a4e77">

**Comment by becem-gharbi** [comment]
Please provide the complete SFC or a reproduction of the issue.

**Comment by Lgowen** [comment]
> Please provide the complete SFC or a reproduction of the issue.

<template>
  <div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <n-form ref="formRef" :model="model" label-placement="left" label-width="auto" require-mark-placement="right-hanging"
      size="medium" :style="{
        maxWidth: '640px'
      }">
      <n-form-item label="page" path="page">
        <n-input v-model:value="model.page" placeholder="本次预览的入口页面路径" />
      </n-form-item>
      <n-form-item label="pageQuery" path="pageQuery">
        <n-input v-model:value="model.pageQuery" placeholder="本次预览的页面参数" />
      </n-form-item>
      <n-form-item label="scene" path="scene">
        <n-select v-model:value="model.scene" placeholder="本次预览的场景值" :options="options" />
      </n-form-item>
      <div style="display: flex; justify-content: flex-end">
        <n-button round type="primary" @click="handleValidateButtonClick">
          生成二维码
        </n-button>
      </div>
    </n-form>

    <pre>{{ JSON.stringify(model, null, 2) }}</pre>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const model = ref({
  page: '/page/index/index',
  pageQuery: '',
  scene: ''
})

const options = ref([
  {
    label: 'ch_appcenter',
    value: 'ch_appcenter'
  },
])

function handleValidateButtonClick() {
  console.log('click me')
}
</script>


@bg-dev/nuxt-naiveui: version 1.6.0
nuxt: version: 3.8.2

**Comment by Lgowen** [comment]
<template>
  <div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <n-form ref="formRef" :model="model" label-placement="left" label-width="auto" require-mark-placement="right-hanging"
      size="medium" :style="{
        maxWidth: '640px'
      }">
      <n-form-item label="page" path="page">
        <n-input v-model:value="model.page" placeholder="本次预览的入口页面路径" />
      </n-form-item>
      <n-form-item label="pageQuery" path="pageQuery">
        <n-input v-model:value="model.pageQuery" placeholder="本次预览的页面参数" />
      </n-form-item>
      <n-form-item label="scene" path="scene">
        <n-select v-model:value="model.scene" placeholder="本次预览的场景值" :options="options" />
      </n-form-item>
      <div style="display: flex; justify-content: flex-end">
        <n-button round type="primary" @click="handleValidateButtonClick">
          生成二维码
        </n-button>
      </div>
    </n-form>

    <pre>{{ JSON.stringify(model, null, 2) }}</pre>
  </div>
</template>

**Comment by Lgowen** [comment]
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <n-form ref="formRef" :model="model" label-placement="left" label-width="auto" require-mark-placement="right-hanging"
      size="medium" :style="{
        maxWidth: '640px'
      }">
      <n-form-item label="page" path="page">
        <n-input v-model:value="model.page" placeholder="本次预览的入口页面路径" />
      </n-form-item>
      <n-form-item label="pageQuery" path="pageQuery">
        <n-input v-model:value="model.pageQuery" placeholder="本次预览的页面参数" />
      </n-form-item>
      <n-form-item label="scene" path="scene">
        <n-select v-model:value="model.scene" placeholder="本次预览的场景值" :options="options" />
      </n-form-item>
      <div style="display: flex; justify-content: flex-end">
        <n-button round type="primary" @click="handleValidateButtonClick">
          生成二维码
        </n-button>
      </div>
    </n-form>
  </div>

**Comment by Lgowen** [comment]
```vue
  <div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <n-form ref="formRef" :model="model" label-placement="left" label-width="auto" require-mark-placement="right-hanging"
      size="medium" :style="{
        maxWidth: '640px'
      }">
      <n-form-item label="page" path="page">
        <n-input v-model:value="model.page" placeholder="本次预览的入口页面路径" />
      </n-form-item>
      <n-form-item label="pageQuery" path="pageQuery">
        <n-input v-model:value="model.pageQuery" placeholder="本次预览的页面参数" />
      </n-form-item>
      <n-form-item label="scene" path="scene">
        <n-select v-model:value="model.scene" placeholder="本次预览的场景值" :options="options" />
      </n-form-item>
      <div style="display: flex; justify-content: flex-end">
        <n-button round type="primary" @click="handleValidateButtonClick">
          生成二维码
        </n-button>
      </div>
    </n-form>

    <pre>{{ JSON.stringify(model, null, 2) }}</pre>
  </div>
```

**Comment by Lgowen** [comment]
> Please provide the complete SFC or a reproduction of the issue.

thats all of my code
nuxt version: 3.8.2

**Comment by becem-gharbi** [comment]
I was able to reproduce the issue. Seems to be related to `naive-ui`. You can try to initialize `model.scene` as `null`.

**Comment by Lgowen** [comment]
> I was able to reproduce the issue. Seems to be related to `naive-ui`. You can try to initialize `model.scene` as `null`.

thanks my bro
It looks my problem
