### ISSUE TITLE
Inquiring about Release Date

### ISSUE THREAD

**Issue by kuizuo** [becem-gharbi/nuxt-naiveui#4]
I would like to know when the stable version is expected to be released, and have you considered contributing to the [nuxt module](https://nuxt.com/modules)

**Comment by becem-gharbi** [comment]
The roadmap i'm currently working on for nuxt-naiveui **beta** branch is as follows:

_Features_:  Add custom components on top of [naive-ui](https://www.naiveui.com) for mobile usage. I consider [ionic](https://ionicframework.com/docs/components) components as a reference.
_Bugs_: Fix issues related to different rendering modes and also PWA.
_Performance_: Optimize memory usage and lighthouse score.

Regarding the **stable** release, i expect it to be by the end of 03/2023.

As for contributing to nuxt modules, i believe it would be great for visibility and community support.
