### ISSUE TITLE
Add to nuxt/modules

### ISSUE THREAD

**Issue by Zihan-Hu** [becem-gharbi/nuxt-naiveui#43]
This package can help many developers, thank you!

Why not add it to https://github.com/nuxt/modules so that more developers can see it?

**Comment by becem-gharbi** [comment]
Hi, thanks for your interest. There is already a request for this and it seems unfavorable by naive-ui maintainers.
https://github.com/07akioni/naive-ui-nuxt-demo/issues/10#issuecomment-1251147753
