### ISSUE TITLE
after hot update, scrollbar scrollTo function undefined

### ISSUE THREAD

**Issue by NaMoCv** [becem-gharbi/nuxt-naiveui#45]
\<template>
    \<n-scrollbar ref="scroller">
        ...
    \</n-scrollbar>
\</template>

\<script setup lang="ts">
const scroller = ref();
onMounted(() => {
    if (currentPath.value.length > 0) {
        scrollToBottom()
    }
});

const scrollToBottom = () => {
    if (scroller.value.scrollTo) {
        scroller.value.scrollTo({ position: 'bottom' })
        console.log(scroller.value)
    } else {
        console.log(scroller.value.scrollTo)
    }
};
\</script>

在1.10版本，随意修改代码，触发hot update后，能在控制台中看到正常的scroller.value信息，但实际上scroller.value.scrollTo是undefined，具体原因我不会找出来。
在1.9版本，能正常运行scroller.value.scrollTo({ position: 'bottom' })。

**Comment by becem-gharbi** [comment]
In version 1.10 `n-scrollbar` is excluded from SSR. On mounted it should be defined and its methods exposed. Please try to disable SSR and let me know of if the issue persists. I will inspect this issue later.

**Comment by NaMoCv** [comment]
> In version 1.10 `n-scrollbar` is excluded from SSR. On mounted it should be defined and its methods exposed. Please try to disable SSR and let me know if the issue persists. I will inspect this issue later.

I set ssr: false in defineNuxtConfig

**Comment by becem-gharbi** [comment]
Hi, 
I'm not able to reproduce the issue. However revert the ssr of `n-scrollbar` because I didn't take into account its usage as standalone component. 
Thanks for opening this issue!
