### ISSUE TITLE
Bug: `Failed to resolve dependency` when using pnpm

### ISSUE THREAD

**Issue by Zihan-Hu** [becem-gharbi/nuxt-naiveui#48]
If using pnpm without `shamefully-hoist`, Nuxt will complain:

```
WARN  Failed to resolve dependency: naive-ui, present in 'optimizeDeps.include'
WARN  Failed to resolve dependency: vueuc, present in 'optimizeDeps.include'
WARN  Failed to resolve dependency: date-fns-tz/formatInTimeZone, present in 'optimizeDeps.include'
```

**Comment by Zihan-Hu** [comment]
This is because pnpm don't hoist dependencies, so `naive-ui` `vueuc` `date-fns-tz` are not present in `node_modules/`.

Maybe... try adding them to `peerDependencies`?

**Comment by becem-gharbi** [comment]
Thanks for this issue. Although I don't see this as bug, It would be nice in term of DX for the module to work with the default pnpm configuration.
Is this solution would require all deps optimized by vite to also be set as peer deps? 
Maybe first we need to evaluate if the optimization is needed in the first place. I followed `naive-ui` setup [here](https://www.naiveui.com/en-US/os-theme/docs/ssr), maybe it is outdated.
