### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by qiuyoo** [becem-gharbi/nuxt-naiveui#50]
Nuxt Build Error: [iconify-download-icons] ❌ 󠀠 [iconify-download-icons] failed to fetch collections from https://icon  ify-icon-sets.vercel.app,
nuxt.config.ts   setting  naiveui,iconDownload=true

**Comment by becem-gharbi** [comment]
https://nuxt-naiveui.bg.tn/components/naive-icon#offline #46
