### ISSUE TITLE
affecting ui

### ISSUE THREAD

**Issue by vaibhav11s** [becem-gharbi/nuxt-naiveui#52]
https://github.com/becem-gharbi/nuxt-naiveui/blob/614a180c92aa934da4effb5349fc466672fedee8/src/runtime/assets/style.css#L2

Effecting other pseudo classes.
overriding `n-button:hover`'s `background-color`
please give option to not use runtime assets, or any solution for this.

**Comment by becem-gharbi** [comment]
Please provide a reproduction to understand the issue.  https://stackblitz.com/github/nuxt/starter/tree/v3

**Comment by vaibhav11s** [comment]
Issue reproduction: https://stackblitz.com/edit/github-u5ex6s

the same thing without using this package works fine.

**Comment by becem-gharbi** [comment]
Thanks for noticing and reporting this bug.
