### ISSUE TITLE
Upgrade to v1.10.3 leads to all of our application buttons being white

### ISSUE THREAD

**Issue by BracketJohn** [becem-gharbi/nuxt-naiveui#56]
Hey there - thanks for this great library @becem-gharbi! (: 

Upgrading from 1.10.2 to 1.10.3 we noticed that all of our buttons (non naive ui buttons) have a white background. Before update:
![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/25911230/5979076d-2bb9-4ea9-9249-3a035a1e293e)

After update (button is "invisible" due to white-on-white):
![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/25911230/b7d57eac-5d6d-4124-b00d-a8edd7843ced)

Looking at the changelog it may be due to global `button` CSS override introduced in https://github.com/becem-gharbi/nuxt-naiveui/commit/97f9c3ea3b9967e6d04c012dd964d3aed49dec0d?

**Comment by becem-gharbi** [comment]
Hi, as the issue of missing button's bg color is encountered on other cases, please provide a reproduction.

**Comment by BracketJohn** [comment]
Agreed, thanks for fixing this ✋
