### ISSUE TITLE
generateColorThemes get wrong color

### ISSUE THREAD

**Issue by transtone** [becem-gharbi/nuxt-naiveui#66]
`v1.12.1`  the primary color is not primary, but primaryHover.

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/46688/44e37cb6-ff5a-490a-9d9a-826b7a96c19d)

**Comment by becem-gharbi** [comment]
Thanks for noticing this issue, the main color is the sixth in palette with index 5 not 6 😅

**Comment by becem-gharbi** [comment]
> how to set the sixth color?

Fixed on [v1.12.2](https://github.com/becem-gharbi/nuxt-naiveui/releases/tag/v1.12.2)
