### ISSUE TITLE
NaiveIcon is displayed with an offset

### ISSUE THREAD

**Issue by freelyn** [becem-gharbi/nuxt-naiveui#71]
NaiveIcon is displayed with an offset. As a backend I use tauri v1.5.1 + nuxt-naiveui v1.13.2 with SSR disabled (the situation is the same with SSR enabled). Perhaps I'm missing something or is this a bug? If you manually set the desired width and height of the range in the browser editor, it works as expected

<img width="568" alt="image" src="https://github.com/becem-gharbi/nuxt-naiveui/assets/79146777/35546ce6-5496-4871-b954-5677c7def1b0">

<img width="668" alt="image" src="https://github.com/becem-gharbi/nuxt-naiveui/assets/79146777/12d590d4-872d-470e-b3a8-62386fc25a46">

**Comment by becem-gharbi** [comment]
Thanks for reporting this issue. I just pushed a patch.

```
npm i @bg-dev/nuxt-naiveui@edge
```
