### ISSUE TITLE
ERROR(vue-tsc)  Property 'themeConfig' does not exist on type '{}'

### ISSUE THREAD

**Issue by ifrvn** [becem-gharbi/nuxt-naiveui#76]
![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/21982381/02d0e879-f039-44db-99f7-537acce45609)

**Comment by becem-gharbi** [comment]
The `naiveui` property in `app.config` is typed [here](https://github.com/becem-gharbi/nuxt-naiveui/blob/916d250813a4644f4e4269bbf45355e79e828e1c/src/runtime/types/index.d.ts#L47). You can try deleting `.nuxt`. If that does not solve the issue, feel free to provide a reproduction.

**Comment by ifrvn** [comment]
Deleting `.nuxt` doesn't work. It seems to be caused by build-time type checking.

```diff
// nuxt.config.ts
export default defineNuxtConfig({
+  typescript: {
+    typeCheck: true,
+    strict: true
+  },
  devtools: { enabled: true },
  modules: ["@bg-dev/nuxt-naiveui"],
})
```

A reproduction repo:  [ifrvn/nuxt-naiveui-issue-76-reproduction](https://github.com/ifrvn/nuxt-naiveui-issue-76-reproduction)

**Comment by becem-gharbi** [comment]
You'll need to enable `skipLibCheck` to avoid the typecheck of imported modules. Does this used to work on previous nuxt versions ?

```diff
  typescript: {
    typeCheck: true,
    strict: true,
+    tsConfig: {
+      compilerOptions: {
+        skipLibCheck: true,
+      },
+    },
  },
```

**Comment by ifrvn** [comment]
Still error. 

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/21982381/83107b7e-2ad3-479a-9b69-5e127c4516e0)

It's been months since the last time checking on this project. It works on 
```
    "@bg-dev/nuxt-naiveui": "~1.10.0",
    "nuxt": "~3.10.0",
```

**Comment by becem-gharbi** [comment]
Thanks for this issue. I just realized that when `skipLibCheck` enabled (default), package types should be defined on `.ts` module instead of `.d.ts` file.

```
npm i @bg-dev/nuxt-naiveui@edge
```

**Comment by becem-gharbi** [comment]
Thanks for this issue. I just pushed a patch.

```bash
npm i @bg-dev/nuxt-naiveui@edge
```

**Comment by ifrvn** [comment]
Thank you so much! `edge.2` patch works now.
