### ISSUE TITLE
nuxt-naiveui + nuxt-tailwind =  wrong colors. 

### ISSUE THREAD

**Issue by mttzzz** [becem-gharbi/nuxt-naiveui#8]
<n-button type="primary">sss</n-button>

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/16290052/46cea955-ae79-4660-91e4-122c68a03043)

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/16290052/2ef81c09-a435-4029-9bd7-c0b9059a3aeb)

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/16290052/d7ef6b90-37c8-4811-abd3-10bb75847d28)

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/16290052/84a23714-feb9-48a6-b17b-c847c5ee78c0)

**Comment by becem-gharbi** [comment]
Please describe the issue

**Comment by mttzzz** [comment]
Hi! new fresh install nuxt 3 (3.6.2). I add nuxt-naiveui and render <n-button type="primary>sss</n-button. All fine. 

Ather that i add nuxt-tailwind module. And button broken.  Somthing with CSS.

**Comment by becem-gharbi** [comment]
Did you use `NaiveConfig` as root component?

**Comment by mttzzz** [comment]
yes
![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/16290052/f7eb1c43-556d-495f-98af-e9156b91eb8b)

**Comment by mttzzz** [comment]
No. this helps! Thx!!! Is this info in doc and i dont saw it?

**Comment by becem-gharbi** [comment]
It is in **Notes**

**Comment by mttzzz** [comment]
one mo problem. When i build for production  same shit. Can u help?

**Comment by becem-gharbi** [comment]
No problem, what is the environment and rendering mode ?

**Comment by mttzzz** [comment]
https://llama.pushka.biz/ issue here.

**Comment by becem-gharbi** [comment]
Apparently tailwind in overriding the `background-color`.  As a workaround you can add this style to `app.vue`. Can you provide your tailwind configurations ?

```css
.n-button {
    background-color: var(--n-color) !important;
}
```

**Comment by mttzzz** [comment]
thx. this is works.

**Comment by tobiasdiez** [comment]
I can confirm that this workaround works. Would it be possible to add this automatically in `NuxtConfig`?

**Comment by becem-gharbi** [comment]
The style is already there, [reference](https://github.com/becem-gharbi/nuxt-naiveui/blob/ec4f85584655dbff7521302e965dd257b0559d57/src/runtime/components/NaiveConfig.vue#L308). By adding `!important` rule we insure it overrides `Tailwind` style reset. I have worked in several projects with the module and i didn't came across this issue. If you can provide a reproduction this would be helpfull.
