### ISSUE TITLE
NaiveConfig didn't pass locale prop to NConfigProvider

### ISSUE THREAD

**Issue by gjfLeo** [becem-gharbi/nuxt-naiveui#82]
I have set the `locale` and `dateLocale` props for the `NaiveConfig` component, but they do not seem to take effect on the `NConfigProvider`. Is there a way to set the locale?

**Comment by becem-gharbi** [comment]
Thanks for reporting this issue.

**Comment by typed-sigterm** [comment]
Can we release it now?

**Comment by typed-sigterm** [comment]
WTF the GitHub Bug?

![image](https://github.com/user-attachments/assets/3717283f-680c-4fbe-97fa-840c940cbf50)
