### ISSUE TITLE
Difference with other nuxt module

### ISSUE THREAD

**Issue by tobiasdiez** [becem-gharbi/nuxt-naiveui#9]
What's the difference between this module and https://github.com/huntersofbook/naive-ui-nuxt/ ?

(Maybe it would make sense to combine efforts and merge these projects if the goals and approaches overlap enough.)

**Comment by becem-gharbi** [comment]
I don't know much about [naive-ui-nuxt](https://github.com/huntersofbook/naive-ui-nuxt). From docs I would say it's Naive UI with SSR support.

However, this module [nuxt-naiveui](https://github.com/becem-gharbi/nuxt-naiveui) goes beyond this. It's intended to be used as a complete UI layer with friendly Tailwind integration, built-in color mode, large icon library, device base theming plus essential components that are not currently found in Naive UI.

**Comment by tobiasdiez** [comment]
Thanks a lot for the explanation! Migration to your module was easy enough and everything works like a charm. Thanks for your work on this module!
